---
title: "kareldierickx_rotation_analyse_transveg"
author: "Todi Daelman"
date: "2024-02-28"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE)
# options(paged.print=FALSE) #output of tables as in console and not as tibble

library(lidR)
library(raster)
library(rgl)          #3D plotting
library(rasterVis)    #3D plotting of a raster
library(plot3D)
library(sf)
library(terra)
library(dplyr)
library(lubridate)    #date handeling
library(ggnewscale)   #introduce new color scale in plots 
library(ggplot2)      #
library(patchwork)    #stick different plots to each other
library(animation)
library(viridis)
library(cowplot)      #adding title to combined plots with plot_grid
library(egg)          #ggcombine function
library(ggpubr)       #annotate_figure function
library(purrr)
library(factoextra)   #visualising clusters
library(ggridges)     #ridgeline plots
library(grid)         #combining plots
library(hrbrthemes)   #plotting themes and fonts
library(broom)        #model stats manipulation

source("../functions/mrt_average.r")
source("../functions/gplot_data.r")
source("../functions/mrt_cropping.r")
source("../functions/mrt_plotting_vegtrans.r")
source("../functions/rasterlist_to_df.r")
source("../functions/shade_analyser.r")
source("../functions/delta_hour_plotting.R")
source("../functions/raster_list_to_delta_df.R")
```


```{r}
simulation_output_folder <- file.path(rotation_folder_path, "solweig_output/simulation_output")

street_extent_path <- file.path(rotation_folder_path, "street_raster.tif")
street_extent <- raster(street_extent_path) #used to be clip_extent, a shp file
# clip_extent <- st_read(clip_extent_path) 

DSM_background_path <- file.path(rotation_folder_path, "DSM.tif")
DSM_background <- raster(DSM_background_path)

DSM_background_df <- gplot_data(DSM_background)

```


```{r}
## all rotation scenarios

# scenario selecteren

# Get the list of all folders starting with "simulation_"

rotation_folder_path <- "C:/Users/todaelma/OneDrive - UGent/Documents/PhD/QGIS/SOLWEIG/test-Gent/generated SOLWEIG input/kareldierickx_rotation"


folder_list <- list.dirs(path = rotation_folder_path, full.names = TRUE, recursive = FALSE)

# Extract numerical value from folder names
numeric_values <- as.numeric(gsub(".*r_(\\d+)$", "\\1", folder_list))

# Order the folder list based on numeric values
folder_list <- folder_list[order(numeric_values)]

for (rotation_folder in folder_list){
  
  rotation_angle <- as.numeric(gsub(".*r_(\\d+)$", "\\1", rotation_folder))
  folder_name <- gsub(".*/([^/]+)/?$", "\\1", rotation_folder)
  
  # Create the folder path
  figure_output_folder <- file.path("figures", "rotation4", folder_name)
  
  simulation_output_folder <- file.path(rotation_folder, "solweig_output/simulation_output")
  
  street_extent_path <- file.path(rotation_folder, "street_raster.tif")
  street_extent <- raster(street_extent_path) #used to be clip_extent, a shp file  
  
  raster_list_full <- mrt_cropping(simulation_output_folder, street_extent, search_variable = "transveg", time_of_interest = "D")
  
  hour_summary_df <- data.frame()
  
  for (i in 1:(length(raster_list_full)-1)) {
    
    print(i)
    
    scenario <- names(raster_list_full)[i+1]
    print(scenario)
    
    delta_df <- raster_list_to_delta_df(raster_list_full, scenario)
    
    #SUMMARY DATAFRAME CONSTRUCTION
    hour_summary_df_temp <- raster_list_to_delta_df(raster_list_full, scenario, summary_index = 2)

    hour_summary_df <- rbind(hour_summary_df, hour_summary_df_temp)
    
    
    #PLOTTING
    p <- delta_hour_plotting(delta_df, scenario)

    p + ggtitle(paste0("Street angle: ", rotation_angle+15 ,"° ", "- Scenario: ", scenario)) -> p

    ggsave(paste0(figure_output_folder, "/", scenario, "_deltaT.png"),
         p,
         bg = "white",
         dpi = 300)
    
  }
  
}

```




```{r}
## all rotation scenarios -> create overview list

# scenario selecteren

# Get the list of all folders starting with "simulation_"

rotation_folder_path <- "C:/Users/todaelma/OneDrive - UGent/Documents/PhD/QGIS/SOLWEIG/test-Gent/generated SOLWEIG input/kareldierickx_rotation"


folder_list <- list.dirs(path = rotation_folder_path, full.names = TRUE, recursive = FALSE)

# Extract numerical value from folder names
numeric_values <- as.numeric(gsub(".*r_(\\d+)$", "\\1", folder_list))

# Order the folder list based on numeric values
folder_list <- folder_list[order(numeric_values)]
folder_names <- gsub(".*/([^/]+)/?$", "\\1", folder_list) #N

# initialise complete list with N (for every rotation scenario) lists containing P (for every transveg scenario) dataframes 

delta_df_list_full <- vector("list", length = length(folder_names)) #N
names(delta_df_list_full) <- folder_names

#initialise list to summarise all hourly averaged deltas
hour_summary_df <- data.frame()

#counter for N
N <- 1 

for (rotation_folder in folder_list){ #N
  
  rotation_angle <- as.numeric(gsub(".*r_(\\d+)$", "\\1", rotation_folder))
  folder_name <- gsub(".*/([^/]+)/?$", "\\1", rotation_folder)
  
  # Create the folder path
  figure_output_folder <- file.path("figures", "rotation4", folder_name)
  
  simulation_output_folder <- file.path(rotation_folder, "solweig_output/simulation_output")
  
  street_extent_path <- file.path(rotation_folder, "street_raster.tif")
  street_extent <- raster(street_extent_path) #used to be clip_extent, a shp file  
  
  #opening rasters
  raster_list_full <- mrt_cropping(simulation_output_folder, street_extent, search_variable = "transveg", time_of_interest = "D")
  
  # initialise delta_df for every scenario
  scenario_names <- names(raster_list_full) #P
  
  delta_df_list_scenario <- vector("list", length = length(scenario_names)-1)
  names(delta_df_list_scenario) <- scenario_names[2:length(scenario_names)]
  
  for (i in 1:(length(raster_list_full)-1)) { #P
    
    print(i)
    
    scenario <- names(raster_list_full)[i+1]
    print(scenario)
    
    #analyse the shade
    shade_list_output <- raster_list_to_delta_df(raster_list_full, scenario, summary_index = 4)
    
    delta_df <- shade_list_output[[1]]
    
    #write away the delta_df
    delta_df_list_scenario[[i]] <- delta_df
    
    #SUMMARY DATAFRAME CONSTRUCTION -> TO DO FOR ALL ROTATION. SAVE AS .R FILE IN FOLDER OF SIMULATION
    hour_summary_df_temp <- shade_list_output[[2]]
    
    hour_summary_df_temp %>%
      mutate(rotation_angle = rotation_angle,
             street_angle = -(rotation_angle+15) +360) %>%
      select(scenario, rotation_angle, street_angle, everything()) -> hour_summary_df_temp
    # 
    hour_summary_df <- rbind(hour_summary_df, hour_summary_df_temp)
    # 
    # #PLOTTING
    # p <- delta_hour_plotting(delta_df, scenario)
    # 
    # p + ggtitle(paste0("Street angle: ", rotation_angle+15 ,"° ", "- Scenario: ", scenario)) -> p
    # 
    # ggsave(paste0(figure_output_folder, "/", scenario, "_deltaT.png"),
    #      p,
    #      bg = "white",
    #      dpi = 300)
    
  }
  
  delta_df_list_full[[N]] <- delta_df_list_scenario
  N <- N + 1
  
}


#CHECK OUTPUT
delta_df_list_full
hour_summary_df

## save the list: contains N lists (1 for every rotation), each containing P dfs with delta Tmrt for every scenario  
save(delta_df_list_full, file = "rotation_output_analysis/delta_Tmrt_data/delta_df_list_full.Rdata")

## save the list
save(hour_summary_df, file = "rotation_output_analysis/delta_Tmrt_data/delta_df_hour_full.Rdata")

```



```{r}

# load the full (delte) Tmrt list:
delta_df_list_full <- readRDS("rotation_output_analysis/delta_Tmrt_data/delta_df_list_full.Rdata")

# load the hour summary list:
hour_summary_df <- readRDS("rotation_output_analysis/delta_Tmrt_data/delta_df_hour_full.Rdata")

```


```{r}
# analysis based on overview list with ALL deltas!

## table generation

N_length <- length(delta_df_list_full) #number of rotation angles -> 8 + base = 9
P_length <- length(delta_df_list_full[[1]]) #number of (transveg) scenarios -> 10 (5,10,..., 50)

# initialisation
parameters_summary_df <- c("rot_angle", "street_angle", "transveg", "mean_Tmrt", "median_Tmrt", "mean_delta_Tmrt", "median_delta_Tmrt", "count")

scenario_summary_df_raw <- data.frame(matrix(nrow = N_length*P_length, 
                                         ncol = length(parameters_summary_df)))

names(scenario_summary_df_raw) <- parameters_summary_df


for (N in 1:N_length){
  
  #extract rotation N
  rotation_angle_N <- as.integer(unlist(strsplit(names(delta_df_list_full)[N], "_"))[2])
  street_angle_N <- -(rotation_angle_N + 15) + 360
  
  rotation_list_N <- delta_df_list_full[[N]]
  
  for (P in 1:P_length){
    
    #index of the complete scenario to write away in the summary scenario
    index <- (N-1)*P_length + P

    scenario_summary_df_raw$rot_angle[index] <- rotation_angle_N
    scenario_summary_df_raw$street_angle[index] <- street_angle_N
    
    # scenario_P <- as.integer(tail(unlist(strsplit(names(rotation_list_N)[P], split = "_")), n = 1))
    scenario_P <- names(rotation_list_N)[P]
    scenario_summary_df_raw$transveg[index] <- scenario_P

    #actual delta_df and Tmrt of the scenario
    delta_df_P <- rotation_list_N[[P]]
    
    delta_df_P %>%
      ungroup() %>%
      filter(mm == "shade") %>%
      summarise(mean_Tmrt = mean(Tmrt_reference),
                median_Tmrt = median(Tmrt_reference),
                mean_delta_Tmrt = mean(value),
                median_delta_Tmrt = median(value),
                count = n()) -> delta_df_P_summary
    
    
    scenario_summary_df_raw[index, c("mean_Tmrt", "median_Tmrt", "mean_delta_Tmrt", "median_delta_Tmrt", "count")] <- delta_df_P_summary
    
    
  }
}


#making unique factors of the different scenarios 
scenario_summary_df <- scenario_summary_df_raw %>%
  mutate(street_angle = -(rot_angle + 15) + 360,
         transveg = sapply(strsplit(transveg, split = "_"), function(x) tail(x, n = 1)),
         street_orientation = case_when(
           street_angle == 0 ~ "NS",
           street_angle == 45 ~ "NE-SW",
           street_angle == 90 ~ "EW",
           street_angle == 135 ~ "NW-SE",
           street_angle == 180 ~ "NS",
           street_angle == 225 ~ "NE-SW",
           street_angle == 270 ~ "EW",
           street_angle == 315 ~ "NW-SE",
           street_angle == 345 ~ "base",
           TRUE ~ NA_character_)) %>%
  arrange(street_angle)


#add direction



```



table analysis
```{r}

#plotting transveg(x) vs delta_Tmrt(y)
scenario_summary_df %>%
  mutate(transveg = as.numeric(as.character(transveg)),
         street_angle = factor(street_angle, ordered = TRUE),
         street_orientation = factor(street_orientation)) %>%
  ggplot(aes(x = transveg, y = mean_delta_Tmrt, colour = street_angle)) +
  geom_point() +
  geom_line(aes(linetype = street_orientation)) +
  theme_ipsum()

#constructing linear model 
scenario_summary_df %>%
  mutate(transveg = as.numeric(as.character(transveg)),
         street_angle = as.numeric(as.character(street_angle))) %>%
  nest(data = -street_angle) %>%
  mutate(model = map(data, ~lm(mean_delta_Tmrt ~ transveg, data = .)), tidied = map(model, tidy)) %>% 
  unnest(tidied) -> scenario_fitted_models

#extract slopes
scenario_fitted_models %>%
  filter(term == "transveg") %>%
  mutate(slope = estimate) %>%
  select(street_angle, slope) -> scenario_slopes

#merge slope with full table
summary_slopes <- right_join(scenario_slopes, scenario_summary_df, by = "street_angle")
  
#plotting of slope in function of rotation angle
summary_slopes %>% 
  group_by(street_angle) %>%
  summarise(slope = first(slope)) %>%
  ggplot(aes(x = street_angle, y = slope)) +
  scale_x_continuous(breaks = c(15, seq(45,360,45))) +
  geom_col() +
  theme_ipsum()

# plottins of slope in function of rotation angle (polar coordinates)
summary_slopes %>% 
  group_by(street_angle) %>%
  summarise(slope = first(slope),
            street_orientation = first(street_orientation)) %>%
  ggplot() +
  geom_bar(aes(x = street_angle, y = slope, fill = street_orientation),
           stat = "identity", width = 15) +
  coord_polar() +
  scale_x_continuous(limits = c(0,360),
                     breaks = seq(0,360,45)) +
  labs(x = "Street Angle (degrees)", y = "Slope") +
  theme_minimal()





```

```{r}
## plotting of raster

scenario_summary_df %>%
  ggplot() +
  geom_raster(aes(x = street_angle, y = transveg, fill = mean_delta_Tmrt)) +
  theme_ipsum() +
  scale_fill_distiller(palette = "greens")


##https://stackoverflow.com/questions/61914534/how-to-draw-a-2d-heatmap-in-polar-coordinates-with-ggplot2

scenario_summary_df %>%
  mutate(transveg = as.numeric(as.character(transveg)),
         street_angle = as.numeric(as.character(street_angle))) %>%
  mutate(phi = (180/pi)*atan2(transveg, street_angle),
         r = sqrt(street_angle^2 + transveg^2)) %>%
  ggplot(aes(phi, r, fill = mean_delta_Tmrt)) +
  geom_bin2d() +
  coord_polar(start = 0) +
  scale_fill_distiller(palette = "heat") +
  theme_minimal()


```

